name: git_events_bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: DevTeam - Brain Ring - Notification to the Telegram chat
      uses: actions/checkout@v3
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{github.actor }}: ${{ github.event_name }} to the ${{ github.repository }}.
